namespace SlangShaderSharp;

/// <summary>
///     Severity of a diagnostic generated by the compiler.
///     Values come from the enum below, with higher values representing more severe
///     conditions, and all values >= <see cref="Error"/> indicating compilation
///     failure.
/// </summary>
public enum SlangSeverity : int
{
    /// <summary>
    ///     A message that is disabled, filtered out.
    /// </summary>
    Disabled = 0,

    /// <summary>
    ///     An informative message.
    /// </summary>
    Note = 1,

    /// <summary>
    ///     A warning, which indicates a possible problem.
    /// </summary>
    Warning = 2,

    /// <summary>
    ///     An error, indicating that compilation failed.
    /// </summary>
    Error = 3,

    /// <summary>
    ///     An unrecoverable error, which forced compilation to abort.
    /// </summary>
    Fatal = 4,

    /// <summary>
    ///      An internal error, indicating a logic error in the compiler.
    /// </summary>
    Internal = 5,
}
